/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminLeadAndClientRouteRouteImport } from './routes/admin/lead-and-client/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminDashboardAndAnalyticsIndexRouteImport } from './routes/admin/dashboard-and-analytics/index'
import { Route as AdminOpportunitiesIndexRouteImport } from './routes/admin/opportunities/index'
import { Route as AdminClientClientIdIndexRouteImport } from './routes/admin/client/$clientId/index'
import { Route as AdminLeadAndClientClientsIndexRouteImport } from './routes/admin/lead-and-client/clients/index'
import { Route as AdminLeadAndClientLeadsIndexRouteImport } from './routes/admin/lead-and-client/leads/index'
import { Route as AdminLeadLeadIdIndexRouteImport } from './routes/admin/lead/$leadId/index'
import { Route as AdminLeadCreateIndexRouteImport } from './routes/admin/lead/create/index'
import { Route as AdminOpportunityOpportunityIdIndexRouteImport } from './routes/admin/opportunity/$opportunityId/index'
import { Route as AdminOpportunityCreateIndexRouteImport } from './routes/admin/opportunity/create/index'
import { Route as AdminOpportunityOpportunityIdEditIndexRouteImport } from './routes/admin/opportunity/$opportunityId/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadAndClientRouteRoute = AdminLeadAndClientRouteRouteImport.update({
  id: '/lead-and-client',
  path: '/lead-and-client',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardAndAnalyticsIndexRoute =
  AdminDashboardAndAnalyticsIndexRouteImport.update({
    id: '/dashboard-and-analytics/',
    path: '/dashboard-and-analytics/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOpportunitiesIndexRoute = AdminOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientClientIdIndexRoute =
  AdminClientClientIdIndexRouteImport.update({
    id: '/client/$clientId/',
    path: '/client/$clientId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLeadAndClientClientsIndexRoute =
  AdminLeadAndClientClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AdminLeadAndClientRouteRoute,
  } as any)
const AdminLeadAndClientLeadsIndexRoute =
  AdminLeadAndClientLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AdminLeadAndClientRouteRoute,
  } as any)
const AdminLeadLeadIdIndexRoute = AdminLeadLeadIdIndexRouteImport.update({
  id: '/lead/$leadId/',
  path: '/lead/$leadId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadCreateIndexRoute = AdminLeadCreateIndexRouteImport.update({
  id: '/lead/create/',
  path: '/lead/create/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOpportunityOpportunityIdIndexRoute =
  AdminOpportunityOpportunityIdIndexRouteImport.update({
    id: '/opportunity/$opportunityId/',
    path: '/opportunity/$opportunityId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOpportunityCreateIndexRoute =
  AdminOpportunityCreateIndexRouteImport.update({
    id: '/opportunity/create/',
    path: '/opportunity/create/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOpportunityOpportunityIdEditIndexRoute =
  AdminOpportunityOpportunityIdEditIndexRouteImport.update({
    id: '/opportunity/$opportunityId/edit/',
    path: '/opportunity/$opportunityId/edit/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/lead-and-client': typeof AdminLeadAndClientRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/admin/dashboard-and-analytics/': typeof AdminDashboardAndAnalyticsIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/client/$clientId/': typeof AdminClientClientIdIndexRoute
  '/admin/lead-and-client/clients/': typeof AdminLeadAndClientClientsIndexRoute
  '/admin/lead-and-client/leads/': typeof AdminLeadAndClientLeadsIndexRoute
  '/admin/lead/$leadId/': typeof AdminLeadLeadIdIndexRoute
  '/admin/lead/create/': typeof AdminLeadCreateIndexRoute
  '/admin/opportunity/$opportunityId/': typeof AdminOpportunityOpportunityIdIndexRoute
  '/admin/opportunity/create/': typeof AdminOpportunityCreateIndexRoute
  '/admin/opportunity/$opportunityId/edit/': typeof AdminOpportunityOpportunityIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/lead-and-client': typeof AdminLeadAndClientRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/admin/dashboard-and-analytics': typeof AdminDashboardAndAnalyticsIndexRoute
  '/admin/opportunities': typeof AdminOpportunitiesIndexRoute
  '/admin/client/$clientId': typeof AdminClientClientIdIndexRoute
  '/admin/lead-and-client/clients': typeof AdminLeadAndClientClientsIndexRoute
  '/admin/lead-and-client/leads': typeof AdminLeadAndClientLeadsIndexRoute
  '/admin/lead/$leadId': typeof AdminLeadLeadIdIndexRoute
  '/admin/lead/create': typeof AdminLeadCreateIndexRoute
  '/admin/opportunity/$opportunityId': typeof AdminOpportunityOpportunityIdIndexRoute
  '/admin/opportunity/create': typeof AdminOpportunityCreateIndexRoute
  '/admin/opportunity/$opportunityId/edit': typeof AdminOpportunityOpportunityIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/lead-and-client': typeof AdminLeadAndClientRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/admin/dashboard-and-analytics/': typeof AdminDashboardAndAnalyticsIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/client/$clientId/': typeof AdminClientClientIdIndexRoute
  '/admin/lead-and-client/clients/': typeof AdminLeadAndClientClientsIndexRoute
  '/admin/lead-and-client/leads/': typeof AdminLeadAndClientLeadsIndexRoute
  '/admin/lead/$leadId/': typeof AdminLeadLeadIdIndexRoute
  '/admin/lead/create/': typeof AdminLeadCreateIndexRoute
  '/admin/opportunity/$opportunityId/': typeof AdminOpportunityOpportunityIdIndexRoute
  '/admin/opportunity/create/': typeof AdminOpportunityCreateIndexRoute
  '/admin/opportunity/$opportunityId/edit/': typeof AdminOpportunityOpportunityIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/lead-and-client'
    | '/login/'
    | '/admin/dashboard-and-analytics/'
    | '/admin/opportunities/'
    | '/admin/client/$clientId/'
    | '/admin/lead-and-client/clients/'
    | '/admin/lead-and-client/leads/'
    | '/admin/lead/$leadId/'
    | '/admin/lead/create/'
    | '/admin/opportunity/$opportunityId/'
    | '/admin/opportunity/create/'
    | '/admin/opportunity/$opportunityId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/lead-and-client'
    | '/login'
    | '/admin/dashboard-and-analytics'
    | '/admin/opportunities'
    | '/admin/client/$clientId'
    | '/admin/lead-and-client/clients'
    | '/admin/lead-and-client/leads'
    | '/admin/lead/$leadId'
    | '/admin/lead/create'
    | '/admin/opportunity/$opportunityId'
    | '/admin/opportunity/create'
    | '/admin/opportunity/$opportunityId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/lead-and-client'
    | '/login/'
    | '/admin/dashboard-and-analytics/'
    | '/admin/opportunities/'
    | '/admin/client/$clientId/'
    | '/admin/lead-and-client/clients/'
    | '/admin/lead-and-client/leads/'
    | '/admin/lead/$leadId/'
    | '/admin/lead/create/'
    | '/admin/opportunity/$opportunityId/'
    | '/admin/opportunity/create/'
    | '/admin/opportunity/$opportunityId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lead-and-client': {
      id: '/admin/lead-and-client'
      path: '/lead-and-client'
      fullPath: '/admin/lead-and-client'
      preLoaderRoute: typeof AdminLeadAndClientRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard-and-analytics/': {
      id: '/admin/dashboard-and-analytics/'
      path: '/dashboard-and-analytics'
      fullPath: '/admin/dashboard-and-analytics/'
      preLoaderRoute: typeof AdminDashboardAndAnalyticsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/opportunities/': {
      id: '/admin/opportunities/'
      path: '/opportunities'
      fullPath: '/admin/opportunities/'
      preLoaderRoute: typeof AdminOpportunitiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/client/$clientId/': {
      id: '/admin/client/$clientId/'
      path: '/client/$clientId'
      fullPath: '/admin/client/$clientId/'
      preLoaderRoute: typeof AdminClientClientIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lead-and-client/clients/': {
      id: '/admin/lead-and-client/clients/'
      path: '/clients'
      fullPath: '/admin/lead-and-client/clients/'
      preLoaderRoute: typeof AdminLeadAndClientClientsIndexRouteImport
      parentRoute: typeof AdminLeadAndClientRouteRoute
    }
    '/admin/lead-and-client/leads/': {
      id: '/admin/lead-and-client/leads/'
      path: '/leads'
      fullPath: '/admin/lead-and-client/leads/'
      preLoaderRoute: typeof AdminLeadAndClientLeadsIndexRouteImport
      parentRoute: typeof AdminLeadAndClientRouteRoute
    }
    '/admin/lead/$leadId/': {
      id: '/admin/lead/$leadId/'
      path: '/lead/$leadId'
      fullPath: '/admin/lead/$leadId/'
      preLoaderRoute: typeof AdminLeadLeadIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lead/create/': {
      id: '/admin/lead/create/'
      path: '/lead/create'
      fullPath: '/admin/lead/create/'
      preLoaderRoute: typeof AdminLeadCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/opportunity/$opportunityId/': {
      id: '/admin/opportunity/$opportunityId/'
      path: '/opportunity/$opportunityId'
      fullPath: '/admin/opportunity/$opportunityId/'
      preLoaderRoute: typeof AdminOpportunityOpportunityIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/opportunity/create/': {
      id: '/admin/opportunity/create/'
      path: '/opportunity/create'
      fullPath: '/admin/opportunity/create/'
      preLoaderRoute: typeof AdminOpportunityCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/opportunity/$opportunityId/edit/': {
      id: '/admin/opportunity/$opportunityId/edit/'
      path: '/opportunity/$opportunityId/edit'
      fullPath: '/admin/opportunity/$opportunityId/edit/'
      preLoaderRoute: typeof AdminOpportunityOpportunityIdEditIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminLeadAndClientRouteRouteChildren {
  AdminLeadAndClientClientsIndexRoute: typeof AdminLeadAndClientClientsIndexRoute
  AdminLeadAndClientLeadsIndexRoute: typeof AdminLeadAndClientLeadsIndexRoute
}

const AdminLeadAndClientRouteRouteChildren: AdminLeadAndClientRouteRouteChildren =
  {
    AdminLeadAndClientClientsIndexRoute: AdminLeadAndClientClientsIndexRoute,
    AdminLeadAndClientLeadsIndexRoute: AdminLeadAndClientLeadsIndexRoute,
  }

const AdminLeadAndClientRouteRouteWithChildren =
  AdminLeadAndClientRouteRoute._addFileChildren(
    AdminLeadAndClientRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminLeadAndClientRouteRoute: typeof AdminLeadAndClientRouteRouteWithChildren
  AdminDashboardAndAnalyticsIndexRoute: typeof AdminDashboardAndAnalyticsIndexRoute
  AdminOpportunitiesIndexRoute: typeof AdminOpportunitiesIndexRoute
  AdminClientClientIdIndexRoute: typeof AdminClientClientIdIndexRoute
  AdminLeadLeadIdIndexRoute: typeof AdminLeadLeadIdIndexRoute
  AdminLeadCreateIndexRoute: typeof AdminLeadCreateIndexRoute
  AdminOpportunityOpportunityIdIndexRoute: typeof AdminOpportunityOpportunityIdIndexRoute
  AdminOpportunityCreateIndexRoute: typeof AdminOpportunityCreateIndexRoute
  AdminOpportunityOpportunityIdEditIndexRoute: typeof AdminOpportunityOpportunityIdEditIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLeadAndClientRouteRoute: AdminLeadAndClientRouteRouteWithChildren,
  AdminDashboardAndAnalyticsIndexRoute: AdminDashboardAndAnalyticsIndexRoute,
  AdminOpportunitiesIndexRoute: AdminOpportunitiesIndexRoute,
  AdminClientClientIdIndexRoute: AdminClientClientIdIndexRoute,
  AdminLeadLeadIdIndexRoute: AdminLeadLeadIdIndexRoute,
  AdminLeadCreateIndexRoute: AdminLeadCreateIndexRoute,
  AdminOpportunityOpportunityIdIndexRoute:
    AdminOpportunityOpportunityIdIndexRoute,
  AdminOpportunityCreateIndexRoute: AdminOpportunityCreateIndexRoute,
  AdminOpportunityOpportunityIdEditIndexRoute:
    AdminOpportunityOpportunityIdEditIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
