/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminLeadAndClientRouteRouteImport } from './routes/admin/lead-and-client/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as SurveyTokenRouteImport } from './routes/survey/$token'
import { Route as AdminCommunicationsIndexRouteImport } from './routes/admin/communications/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminOpportunitiesIndexRouteImport } from './routes/admin/opportunities/index'
import { Route as AdminRemindersIndexRouteImport } from './routes/admin/reminders/index'
import { Route as AdminSatisfactionIndexRouteImport } from './routes/admin/satisfaction/index'
import { Route as AdminClientClientIdIndexRouteImport } from './routes/admin/client/$clientId/index'
import { Route as AdminCommunicationsCommunicationIdIndexRouteImport } from './routes/admin/communications/$communicationId/index'
import { Route as AdminCommunicationsCreateIndexRouteImport } from './routes/admin/communications/create/index'
import { Route as AdminLeadAndClientClientsIndexRouteImport } from './routes/admin/lead-and-client/clients/index'
import { Route as AdminLeadAndClientLeadsIndexRouteImport } from './routes/admin/lead-and-client/leads/index'
import { Route as AdminLeadLeadIdIndexRouteImport } from './routes/admin/lead/$leadId/index'
import { Route as AdminLeadCreateIndexRouteImport } from './routes/admin/lead/create/index'
import { Route as AdminOpportunityOpportunityIdIndexRouteImport } from './routes/admin/opportunity/$opportunityId/index'
import { Route as AdminOpportunityCreateIndexRouteImport } from './routes/admin/opportunity/create/index'
import { Route as AdminRemindersReminderIdIndexRouteImport } from './routes/admin/reminders/$reminderId/index'
import { Route as AdminRemindersCreateIndexRouteImport } from './routes/admin/reminders/create/index'
import { Route as AdminSatisfactionClientIdIndexRouteImport } from './routes/admin/satisfaction/$clientId/index'
import { Route as AdminOpportunityOpportunityIdEditIndexRouteImport } from './routes/admin/opportunity/$opportunityId/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadAndClientRouteRoute = AdminLeadAndClientRouteRouteImport.update({
  id: '/lead-and-client',
  path: '/lead-and-client',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyTokenRoute = SurveyTokenRouteImport.update({
  id: '/survey/$token',
  path: '/survey/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunicationsIndexRoute =
  AdminCommunicationsIndexRouteImport.update({
    id: '/communications/',
    path: '/communications/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOpportunitiesIndexRoute = AdminOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRemindersIndexRoute = AdminRemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSatisfactionIndexRoute = AdminSatisfactionIndexRouteImport.update({
  id: '/satisfaction/',
  path: '/satisfaction/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientClientIdIndexRoute =
  AdminClientClientIdIndexRouteImport.update({
    id: '/client/$clientId/',
    path: '/client/$clientId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCommunicationsCommunicationIdIndexRoute =
  AdminCommunicationsCommunicationIdIndexRouteImport.update({
    id: '/communications/$communicationId/',
    path: '/communications/$communicationId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCommunicationsCreateIndexRoute =
  AdminCommunicationsCreateIndexRouteImport.update({
    id: '/communications/create/',
    path: '/communications/create/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLeadAndClientClientsIndexRoute =
  AdminLeadAndClientClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AdminLeadAndClientRouteRoute,
  } as any)
const AdminLeadAndClientLeadsIndexRoute =
  AdminLeadAndClientLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AdminLeadAndClientRouteRoute,
  } as any)
const AdminLeadLeadIdIndexRoute = AdminLeadLeadIdIndexRouteImport.update({
  id: '/lead/$leadId/',
  path: '/lead/$leadId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadCreateIndexRoute = AdminLeadCreateIndexRouteImport.update({
  id: '/lead/create/',
  path: '/lead/create/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOpportunityOpportunityIdIndexRoute =
  AdminOpportunityOpportunityIdIndexRouteImport.update({
    id: '/opportunity/$opportunityId/',
    path: '/opportunity/$opportunityId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOpportunityCreateIndexRoute =
  AdminOpportunityCreateIndexRouteImport.update({
    id: '/opportunity/create/',
    path: '/opportunity/create/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRemindersReminderIdIndexRoute =
  AdminRemindersReminderIdIndexRouteImport.update({
    id: '/reminders/$reminderId/',
    path: '/reminders/$reminderId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRemindersCreateIndexRoute =
  AdminRemindersCreateIndexRouteImport.update({
    id: '/reminders/create/',
    path: '/reminders/create/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminSatisfactionClientIdIndexRoute =
  AdminSatisfactionClientIdIndexRouteImport.update({
    id: '/satisfaction/$clientId/',
    path: '/satisfaction/$clientId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOpportunityOpportunityIdEditIndexRoute =
  AdminOpportunityOpportunityIdEditIndexRouteImport.update({
    id: '/opportunity/$opportunityId/edit/',
    path: '/opportunity/$opportunityId/edit/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/lead-and-client': typeof AdminLeadAndClientRouteRouteWithChildren
  '/survey/$token': typeof SurveyTokenRoute
  '/login/': typeof LoginIndexRoute
  '/admin/communications/': typeof AdminCommunicationsIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/reminders/': typeof AdminRemindersIndexRoute
  '/admin/satisfaction/': typeof AdminSatisfactionIndexRoute
  '/admin/client/$clientId/': typeof AdminClientClientIdIndexRoute
  '/admin/communications/$communicationId/': typeof AdminCommunicationsCommunicationIdIndexRoute
  '/admin/communications/create/': typeof AdminCommunicationsCreateIndexRoute
  '/admin/lead-and-client/clients/': typeof AdminLeadAndClientClientsIndexRoute
  '/admin/lead-and-client/leads/': typeof AdminLeadAndClientLeadsIndexRoute
  '/admin/lead/$leadId/': typeof AdminLeadLeadIdIndexRoute
  '/admin/lead/create/': typeof AdminLeadCreateIndexRoute
  '/admin/opportunity/$opportunityId/': typeof AdminOpportunityOpportunityIdIndexRoute
  '/admin/opportunity/create/': typeof AdminOpportunityCreateIndexRoute
  '/admin/reminders/$reminderId/': typeof AdminRemindersReminderIdIndexRoute
  '/admin/reminders/create/': typeof AdminRemindersCreateIndexRoute
  '/admin/satisfaction/$clientId/': typeof AdminSatisfactionClientIdIndexRoute
  '/admin/opportunity/$opportunityId/edit/': typeof AdminOpportunityOpportunityIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/lead-and-client': typeof AdminLeadAndClientRouteRouteWithChildren
  '/survey/$token': typeof SurveyTokenRoute
  '/login': typeof LoginIndexRoute
  '/admin/communications': typeof AdminCommunicationsIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/opportunities': typeof AdminOpportunitiesIndexRoute
  '/admin/reminders': typeof AdminRemindersIndexRoute
  '/admin/satisfaction': typeof AdminSatisfactionIndexRoute
  '/admin/client/$clientId': typeof AdminClientClientIdIndexRoute
  '/admin/communications/$communicationId': typeof AdminCommunicationsCommunicationIdIndexRoute
  '/admin/communications/create': typeof AdminCommunicationsCreateIndexRoute
  '/admin/lead-and-client/clients': typeof AdminLeadAndClientClientsIndexRoute
  '/admin/lead-and-client/leads': typeof AdminLeadAndClientLeadsIndexRoute
  '/admin/lead/$leadId': typeof AdminLeadLeadIdIndexRoute
  '/admin/lead/create': typeof AdminLeadCreateIndexRoute
  '/admin/opportunity/$opportunityId': typeof AdminOpportunityOpportunityIdIndexRoute
  '/admin/opportunity/create': typeof AdminOpportunityCreateIndexRoute
  '/admin/reminders/$reminderId': typeof AdminRemindersReminderIdIndexRoute
  '/admin/reminders/create': typeof AdminRemindersCreateIndexRoute
  '/admin/satisfaction/$clientId': typeof AdminSatisfactionClientIdIndexRoute
  '/admin/opportunity/$opportunityId/edit': typeof AdminOpportunityOpportunityIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/lead-and-client': typeof AdminLeadAndClientRouteRouteWithChildren
  '/survey/$token': typeof SurveyTokenRoute
  '/login/': typeof LoginIndexRoute
  '/admin/communications/': typeof AdminCommunicationsIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/reminders/': typeof AdminRemindersIndexRoute
  '/admin/satisfaction/': typeof AdminSatisfactionIndexRoute
  '/admin/client/$clientId/': typeof AdminClientClientIdIndexRoute
  '/admin/communications/$communicationId/': typeof AdminCommunicationsCommunicationIdIndexRoute
  '/admin/communications/create/': typeof AdminCommunicationsCreateIndexRoute
  '/admin/lead-and-client/clients/': typeof AdminLeadAndClientClientsIndexRoute
  '/admin/lead-and-client/leads/': typeof AdminLeadAndClientLeadsIndexRoute
  '/admin/lead/$leadId/': typeof AdminLeadLeadIdIndexRoute
  '/admin/lead/create/': typeof AdminLeadCreateIndexRoute
  '/admin/opportunity/$opportunityId/': typeof AdminOpportunityOpportunityIdIndexRoute
  '/admin/opportunity/create/': typeof AdminOpportunityCreateIndexRoute
  '/admin/reminders/$reminderId/': typeof AdminRemindersReminderIdIndexRoute
  '/admin/reminders/create/': typeof AdminRemindersCreateIndexRoute
  '/admin/satisfaction/$clientId/': typeof AdminSatisfactionClientIdIndexRoute
  '/admin/opportunity/$opportunityId/edit/': typeof AdminOpportunityOpportunityIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/lead-and-client'
    | '/survey/$token'
    | '/login/'
    | '/admin/communications/'
    | '/admin/dashboard/'
    | '/admin/opportunities/'
    | '/admin/reminders/'
    | '/admin/satisfaction/'
    | '/admin/client/$clientId/'
    | '/admin/communications/$communicationId/'
    | '/admin/communications/create/'
    | '/admin/lead-and-client/clients/'
    | '/admin/lead-and-client/leads/'
    | '/admin/lead/$leadId/'
    | '/admin/lead/create/'
    | '/admin/opportunity/$opportunityId/'
    | '/admin/opportunity/create/'
    | '/admin/reminders/$reminderId/'
    | '/admin/reminders/create/'
    | '/admin/satisfaction/$clientId/'
    | '/admin/opportunity/$opportunityId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/lead-and-client'
    | '/survey/$token'
    | '/login'
    | '/admin/communications'
    | '/admin/dashboard'
    | '/admin/opportunities'
    | '/admin/reminders'
    | '/admin/satisfaction'
    | '/admin/client/$clientId'
    | '/admin/communications/$communicationId'
    | '/admin/communications/create'
    | '/admin/lead-and-client/clients'
    | '/admin/lead-and-client/leads'
    | '/admin/lead/$leadId'
    | '/admin/lead/create'
    | '/admin/opportunity/$opportunityId'
    | '/admin/opportunity/create'
    | '/admin/reminders/$reminderId'
    | '/admin/reminders/create'
    | '/admin/satisfaction/$clientId'
    | '/admin/opportunity/$opportunityId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/lead-and-client'
    | '/survey/$token'
    | '/login/'
    | '/admin/communications/'
    | '/admin/dashboard/'
    | '/admin/opportunities/'
    | '/admin/reminders/'
    | '/admin/satisfaction/'
    | '/admin/client/$clientId/'
    | '/admin/communications/$communicationId/'
    | '/admin/communications/create/'
    | '/admin/lead-and-client/clients/'
    | '/admin/lead-and-client/leads/'
    | '/admin/lead/$leadId/'
    | '/admin/lead/create/'
    | '/admin/opportunity/$opportunityId/'
    | '/admin/opportunity/create/'
    | '/admin/reminders/$reminderId/'
    | '/admin/reminders/create/'
    | '/admin/satisfaction/$clientId/'
    | '/admin/opportunity/$opportunityId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SurveyTokenRoute: typeof SurveyTokenRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lead-and-client': {
      id: '/admin/lead-and-client'
      path: '/lead-and-client'
      fullPath: '/admin/lead-and-client'
      preLoaderRoute: typeof AdminLeadAndClientRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$token': {
      id: '/survey/$token'
      path: '/survey/$token'
      fullPath: '/survey/$token'
      preLoaderRoute: typeof SurveyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/communications/': {
      id: '/admin/communications/'
      path: '/communications'
      fullPath: '/admin/communications/'
      preLoaderRoute: typeof AdminCommunicationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/opportunities/': {
      id: '/admin/opportunities/'
      path: '/opportunities'
      fullPath: '/admin/opportunities/'
      preLoaderRoute: typeof AdminOpportunitiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reminders/': {
      id: '/admin/reminders/'
      path: '/reminders'
      fullPath: '/admin/reminders/'
      preLoaderRoute: typeof AdminRemindersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/satisfaction/': {
      id: '/admin/satisfaction/'
      path: '/satisfaction'
      fullPath: '/admin/satisfaction/'
      preLoaderRoute: typeof AdminSatisfactionIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/client/$clientId/': {
      id: '/admin/client/$clientId/'
      path: '/client/$clientId'
      fullPath: '/admin/client/$clientId/'
      preLoaderRoute: typeof AdminClientClientIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/communications/$communicationId/': {
      id: '/admin/communications/$communicationId/'
      path: '/communications/$communicationId'
      fullPath: '/admin/communications/$communicationId/'
      preLoaderRoute: typeof AdminCommunicationsCommunicationIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/communications/create/': {
      id: '/admin/communications/create/'
      path: '/communications/create'
      fullPath: '/admin/communications/create/'
      preLoaderRoute: typeof AdminCommunicationsCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lead-and-client/clients/': {
      id: '/admin/lead-and-client/clients/'
      path: '/clients'
      fullPath: '/admin/lead-and-client/clients/'
      preLoaderRoute: typeof AdminLeadAndClientClientsIndexRouteImport
      parentRoute: typeof AdminLeadAndClientRouteRoute
    }
    '/admin/lead-and-client/leads/': {
      id: '/admin/lead-and-client/leads/'
      path: '/leads'
      fullPath: '/admin/lead-and-client/leads/'
      preLoaderRoute: typeof AdminLeadAndClientLeadsIndexRouteImport
      parentRoute: typeof AdminLeadAndClientRouteRoute
    }
    '/admin/lead/$leadId/': {
      id: '/admin/lead/$leadId/'
      path: '/lead/$leadId'
      fullPath: '/admin/lead/$leadId/'
      preLoaderRoute: typeof AdminLeadLeadIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lead/create/': {
      id: '/admin/lead/create/'
      path: '/lead/create'
      fullPath: '/admin/lead/create/'
      preLoaderRoute: typeof AdminLeadCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/opportunity/$opportunityId/': {
      id: '/admin/opportunity/$opportunityId/'
      path: '/opportunity/$opportunityId'
      fullPath: '/admin/opportunity/$opportunityId/'
      preLoaderRoute: typeof AdminOpportunityOpportunityIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/opportunity/create/': {
      id: '/admin/opportunity/create/'
      path: '/opportunity/create'
      fullPath: '/admin/opportunity/create/'
      preLoaderRoute: typeof AdminOpportunityCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reminders/$reminderId/': {
      id: '/admin/reminders/$reminderId/'
      path: '/reminders/$reminderId'
      fullPath: '/admin/reminders/$reminderId/'
      preLoaderRoute: typeof AdminRemindersReminderIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reminders/create/': {
      id: '/admin/reminders/create/'
      path: '/reminders/create'
      fullPath: '/admin/reminders/create/'
      preLoaderRoute: typeof AdminRemindersCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/satisfaction/$clientId/': {
      id: '/admin/satisfaction/$clientId/'
      path: '/satisfaction/$clientId'
      fullPath: '/admin/satisfaction/$clientId/'
      preLoaderRoute: typeof AdminSatisfactionClientIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/opportunity/$opportunityId/edit/': {
      id: '/admin/opportunity/$opportunityId/edit/'
      path: '/opportunity/$opportunityId/edit'
      fullPath: '/admin/opportunity/$opportunityId/edit/'
      preLoaderRoute: typeof AdminOpportunityOpportunityIdEditIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminLeadAndClientRouteRouteChildren {
  AdminLeadAndClientClientsIndexRoute: typeof AdminLeadAndClientClientsIndexRoute
  AdminLeadAndClientLeadsIndexRoute: typeof AdminLeadAndClientLeadsIndexRoute
}

const AdminLeadAndClientRouteRouteChildren: AdminLeadAndClientRouteRouteChildren =
  {
    AdminLeadAndClientClientsIndexRoute: AdminLeadAndClientClientsIndexRoute,
    AdminLeadAndClientLeadsIndexRoute: AdminLeadAndClientLeadsIndexRoute,
  }

const AdminLeadAndClientRouteRouteWithChildren =
  AdminLeadAndClientRouteRoute._addFileChildren(
    AdminLeadAndClientRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminLeadAndClientRouteRoute: typeof AdminLeadAndClientRouteRouteWithChildren
  AdminCommunicationsIndexRoute: typeof AdminCommunicationsIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminOpportunitiesIndexRoute: typeof AdminOpportunitiesIndexRoute
  AdminRemindersIndexRoute: typeof AdminRemindersIndexRoute
  AdminSatisfactionIndexRoute: typeof AdminSatisfactionIndexRoute
  AdminClientClientIdIndexRoute: typeof AdminClientClientIdIndexRoute
  AdminCommunicationsCommunicationIdIndexRoute: typeof AdminCommunicationsCommunicationIdIndexRoute
  AdminCommunicationsCreateIndexRoute: typeof AdminCommunicationsCreateIndexRoute
  AdminLeadLeadIdIndexRoute: typeof AdminLeadLeadIdIndexRoute
  AdminLeadCreateIndexRoute: typeof AdminLeadCreateIndexRoute
  AdminOpportunityOpportunityIdIndexRoute: typeof AdminOpportunityOpportunityIdIndexRoute
  AdminOpportunityCreateIndexRoute: typeof AdminOpportunityCreateIndexRoute
  AdminRemindersReminderIdIndexRoute: typeof AdminRemindersReminderIdIndexRoute
  AdminRemindersCreateIndexRoute: typeof AdminRemindersCreateIndexRoute
  AdminSatisfactionClientIdIndexRoute: typeof AdminSatisfactionClientIdIndexRoute
  AdminOpportunityOpportunityIdEditIndexRoute: typeof AdminOpportunityOpportunityIdEditIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLeadAndClientRouteRoute: AdminLeadAndClientRouteRouteWithChildren,
  AdminCommunicationsIndexRoute: AdminCommunicationsIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminOpportunitiesIndexRoute: AdminOpportunitiesIndexRoute,
  AdminRemindersIndexRoute: AdminRemindersIndexRoute,
  AdminSatisfactionIndexRoute: AdminSatisfactionIndexRoute,
  AdminClientClientIdIndexRoute: AdminClientClientIdIndexRoute,
  AdminCommunicationsCommunicationIdIndexRoute:
    AdminCommunicationsCommunicationIdIndexRoute,
  AdminCommunicationsCreateIndexRoute: AdminCommunicationsCreateIndexRoute,
  AdminLeadLeadIdIndexRoute: AdminLeadLeadIdIndexRoute,
  AdminLeadCreateIndexRoute: AdminLeadCreateIndexRoute,
  AdminOpportunityOpportunityIdIndexRoute:
    AdminOpportunityOpportunityIdIndexRoute,
  AdminOpportunityCreateIndexRoute: AdminOpportunityCreateIndexRoute,
  AdminRemindersReminderIdIndexRoute: AdminRemindersReminderIdIndexRoute,
  AdminRemindersCreateIndexRoute: AdminRemindersCreateIndexRoute,
  AdminSatisfactionClientIdIndexRoute: AdminSatisfactionClientIdIndexRoute,
  AdminOpportunityOpportunityIdEditIndexRoute:
    AdminOpportunityOpportunityIdEditIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SurveyTokenRoute: SurveyTokenRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
